# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  tag: v1.0.0
service:
  name: Node
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
hpa:
  enabled: false
  maxReplicas: 3
istio:
  enabled: false
  weight: 100
